### ISSUE TITLE
Always generating sheets as right_to_left

### ISSUE THREAD

**Issue by Alan-M-Thomaz** [Paxa/fast_excel#46]
no matters what i do, it always create the sheets as right_to_left, even if right_to_left was never called, i tried things like:
`worksheet[:right_to_left]=0`
`worksheet[:right_to_left]=1`
`worksheet[:right_to_left]=false`
`worksheet.right_to_left`
none gave me a normal left-to-right sheet

**Comment by Paxa** [comment]
Hi, I actually found a bug in property mapping, probably you set `print_gridlines` or `print_headers`.
I just pushed a fix, try to use it from master, hopefully should work

**Comment by Alan-M-Thomaz** [comment]
Thx for the quick reply.
But the problem persist.

After some testing found that it happens when i have the gem *pry-rails* installed

gemfile info:
```
gem 'pry-rails'
gem 'rails', '~> 3.2.3'
```
gemfilelock:
```
pry-rails (0.3.9)
  pry (>= 0.10.4)
```
ruby version 2.3.8

**Comment by Paxa** [comment]
I don't use this lib, so didn't notice this bug. (btw with new ruby we can just type `binding.irb`)
Can you share output of
```ruby
FastExcel.print_ffi_obj(workbook)
```
With and without `pry-rails`

**Comment by Alan-M-Thomaz** [comment]
using the example from read.me
with `pry-rails`
```Libxlsxwriter::Workbook
* file: nil
* sheets: #<Libxlsxwriter::Sheets:0x000055facc1aa000>
* worksheets: #<Libxlsxwriter::Worksheets:0x000055facc1a92e0>
* chartsheets: #<FFI::Pointer address=0x000055fad57e7750>
* worksheet_names: #<Libxlsxwriter::WorksheetNames:0x000055facc1a8318>
* chartsheet_names: #<FFI::Pointer address=0x000055fad57e7790>
* charts: #<Libxlsxwriter::Charts:0x000055facc1ae3f8>
* ordered_charts: #<Libxlsxwriter::Charts:0x000055facc1ad390>
* formats: #<Libxlsxwriter::Formats:0x000055facc1ac6e8>
* defined_names: #<Libxlsxwriter::DefinedNames:0x000055facc1c3898>
* sst: #<Libxlsxwriter::Sst:0x000055facc1c28a8>
* properties: #<Libxlsxwriter::DocProperties:0x000055facc1c1d90>
* custom_properties: #<Libxlsxwriter::CustomProperties:0x000055facc1c0378>
* filename: #<FFI::Pointer address=0x000055fad57cb070>
* options: #<Libxlsxwriter::WorkbookOptions:0x000055facc1c40e0>
* num_sheets: 1
* num_worksheets: 1
* num_chartsheets: 0
* first_sheet: 0
* active_sheet: 0
* num_xf_formats: 0
* num_format_count: 0
* drawing_count: 0
* font_count: 0
* border_count: 0
* fill_count: 0
* optimize: 0
* has_png: 0
* has_jpeg: 0
* has_bmp: 0
* used_xf_formats: #<Libxlsxwriter::HashTable:0x000055facc1e1d98>
* vba_project: nil
* vba_codename: nil
```
also calling it to the worksheet
```Libxlsxwriter::Worksheet
* file: #<FFI::Pointer address=0x000055fad56d6490>
* optimize_tmpfile: #<FFI::Pointer address=0x000055fad56d6490>
* table: #<Libxlsxwriter::TableRows:0x000055facc2c2b90>
* hyperlinks: #<Libxlsxwriter::TableRows:0x000055facc2c0c78>
* array: #<FFI::Pointer address=0x000055fad5964350>
* merged_ranges: #<Libxlsxwriter::MergedRanges:0x000055facc2c6268>
* selections: #<Libxlsxwriter::Selections:0x000055facc2c4ff8>
* data_validations: #<FFI::Pointer address=0x000055fad5984c00>
* image_data: #<Libxlsxwriter::ImageData:0x000055facc2cf818>
* chart_data: #<Libxlsxwriter::ChartData:0x000055facc2cdbf8>
* dim_rowmin: 0
* dim_rowmax: 1001
* dim_colmin: 0
* dim_colmax: 2
* sst: #<Libxlsxwriter::Sst:0x000055facc2d69b0>
* name: "Example Report"
* quoted_name: "'Example Report'"
* tmpdir: nil
* index: 0
* active: 0
* selected: 0
* hidden: 0
* active_sheet: #<FFI::Pointer address=0x000055fad57e76d0>
* first_sheet: #<FFI::Pointer address=0x000055fad57e76ce>
* is_chartsheet: 0
* col_options: #<FFI::Pointer address=0x000055fad5984360>
* col_options_max: 128
* col_sizes: nil
* col_sizes_max: 0
* col_formats: #<FFI::Pointer address=0x000055fad5984770>
* col_formats_max: 128
* col_size_changed: 1
* row_size_changed: 0
* optimize: 1
* optimize_row: #<FFI::Pointer address=0x000055fad595ad30>
* fit_height: 0
* fit_width: 0
* horizontal_dpi: 0
* hlink_count: 0
* page_start: 0
* print_scale: 100
* rel_count: 0
* vertical_dpi: 0
* zoom: 100
* filter_on: 0
* fit_page: 0
* hcenter: 0
* orientation: 1
* outline_changed: 0
* outline_on: 1
* outline_style: 1
* outline_below: 1
* outline_right: 0
* page_order: 0
* page_setup_changed: 0
* page_view: 0
* paper_size: 0
* print_gridlines: 0
* print_headers: 0
* print_options_changed: 0
* right_to_left: 1
* screen_gridlines: 1
* show_zeros: 1
* vcenter: 0
* zoom_scale_normal: 1
* num_validations: 0
* vba_codename: nil
* tab_color: -1
* margin_left: 0.7
* margin_right: 0.7
* margin_top: 0.75
* margin_bottom: 0.75
* margin_header: 0.3
* margin_footer: 0.3
* default_row_height: 15.0
* default_row_pixels: 20
* default_col_pixels: 64
* default_row_zeroed: 0
* default_row_set: 0
* header_footer_changed: 0
* header: ""
* footer: ""
* repeat_rows: #<Libxlsxwriter::RepeatRows:0x000055facc304888>
* repeat_cols: #<Libxlsxwriter::RepeatCols:0x000055facc3179b0>
* print_area: #<Libxlsxwriter::PrintArea:0x000055facc3164e8>
* autofilter: #<Libxlsxwriter::Autofilter:0x000055facc3143c8>
* merged_range_count: 0
* hbreaks: nil
* vbreaks: nil
* hbreaks_count: 0
* vbreaks_count: 0
* external_hyperlinks: #<FFI::Pointer address=0x000055fad5984c20>
* external_drawing_links: #<FFI::Pointer address=0x000055fad5984c40>
* drawing_links: #<FFI::Pointer address=0x000055fad5984c60>
* panes: #<Libxlsxwriter::Panes:0x000055facc32f510>
* protection: #<Libxlsxwriter::Protection:0x000055facc32e390>
* drawing: #<Libxlsxwriter::Drawing:0x000055facc32d760>
* list_pointers: #<Libxlsxwriter::WorksheetListPointers:0x000055facc32c0b8>
```

without `pry-rails`
```
Libxlsxwriter::Workbook
* file: nil
* sheets: #<Libxlsxwriter::Sheets:0x00005582b6e67a10>
* worksheets: #<Libxlsxwriter::Worksheets:0x00005582b6e67650>
* chartsheets: #<FFI::Pointer address=0x00005582b46b6330>
* worksheet_names: #<Libxlsxwriter::WorksheetNames:0x00005582b6e67100>
* chartsheet_names: #<FFI::Pointer address=0x00005582b2f4bb70>
* charts: #<Libxlsxwriter::Charts:0x00005582b6e66bb0>
* ordered_charts: #<Libxlsxwriter::Charts:0x00005582b6e66818>
* formats: #<Libxlsxwriter::Formats:0x00005582b6e66480>
* defined_names: #<Libxlsxwriter::DefinedNames:0x00005582b6e660e8>
* sst: #<Libxlsxwriter::Sst:0x00005582b6e65d50>
* properties: #<Libxlsxwriter::DocProperties:0x00005582b6e659b8>
* custom_properties: #<Libxlsxwriter::CustomProperties:0x00005582b6e65620>
* filename: #<FFI::Pointer address=0x00005582b51e9700>
* options: #<Libxlsxwriter::WorkbookOptions:0x00005582b6e650d0>
* num_sheets: 1
* num_worksheets: 1
* num_chartsheets: 0
* first_sheet: 0
* active_sheet: 0
* num_xf_formats: 0
* num_format_count: 0
* drawing_count: 0
* font_count: 0
* border_count: 0
* fill_count: 0
* optimize: 0
* has_png: 0
* has_jpeg: 0
* has_bmp: 0
* used_xf_formats: #<Libxlsxwriter::HashTable:0x00005582b6e643d8>
* vba_project: nil
* vba_codename: nil
```
worksheet
```
Libxlsxwriter::Worksheet
* file: #<FFI::Pointer address=0x00005582b42af7b0>
* optimize_tmpfile: #<FFI::Pointer address=0x00005582b42af7b0>
* table: #<Libxlsxwriter::TableRows:0x00005582b6e6b8b8>
* hyperlinks: #<Libxlsxwriter::TableRows:0x00005582b6e6b520>
* array: #<FFI::Pointer address=0x00005582b6d93fe0>
* merged_ranges: #<Libxlsxwriter::MergedRanges:0x00005582b6e6afd0>
* selections: #<Libxlsxwriter::Selections:0x00005582b6e6ac38>
* data_validations: #<FFI::Pointer address=0x00005582b1f03460>
* image_data: #<Libxlsxwriter::ImageData:0x00005582b6e6a6e8>
* chart_data: #<Libxlsxwriter::ChartData:0x00005582b6e6a350>
* dim_rowmin: 0
* dim_rowmax: 1001
* dim_colmin: 0
* dim_colmax: 2
* sst: #<Libxlsxwriter::Sst:0x00005582b6e69d38>
* name: "Example Report"
* quoted_name: "'Example Report'"
* tmpdir: nil
* index: 0
* active: 0
* selected: 0
* hidden: 0
* active_sheet: #<FFI::Pointer address=0x00005582b6277d40>
* first_sheet: #<FFI::Pointer address=0x00005582b6277d3e>
* is_chartsheet: 0
* col_options: #<FFI::Pointer address=0x00005582b5fbb930>
* col_options_max: 128
* col_sizes: nil
* col_sizes_max: 0
* col_formats: #<FFI::Pointer address=0x00005582b2d28490>
* col_formats_max: 128
* col_size_changed: 1
* row_size_changed: 0
* optimize: 1
* optimize_row: #<FFI::Pointer address=0x00005582b670a000>
* fit_height: 0
* fit_width: 0
* horizontal_dpi: 0
* hlink_count: 0
* page_start: 0
* print_scale: 100
* rel_count: 0
* vertical_dpi: 0
* zoom: 100
* filter_on: 0
* fit_page: 0
* hcenter: 0
* orientation: 1
* outline_changed: 0
* outline_on: 1
* outline_style: 1
* outline_below: 1
* outline_right: 0
* page_order: 0
* page_setup_changed: 0
* page_view: 0
* paper_size: 0
* print_gridlines: 0
* print_headers: 0
* print_options_changed: 0
* right_to_left: 0
* screen_gridlines: 1
* show_zeros: 1
* vcenter: 0
* zoom_scale_normal: 1
* num_validations: 0
* vba_codename: nil
* tab_color: -1
* margin_left: 0.7
* margin_right: 0.7
* margin_top: 0.75
* margin_bottom: 0.75
* margin_header: 0.3
* margin_footer: 0.3
* default_row_height: 15.0
* default_row_pixels: 20
* default_col_pixels: 64
* default_row_zeroed: 0
* default_row_set: 0
* header_footer_changed: 0
* header: ""
* footer: ""
* repeat_rows: #<Libxlsxwriter::RepeatRows:0x00005582b5e1e488>
* repeat_cols: #<Libxlsxwriter::RepeatCols:0x00005582b5e1e0c8>
* print_area: #<Libxlsxwriter::PrintArea:0x00005582b5e1dce0>
* autofilter: #<Libxlsxwriter::Autofilter:0x00005582b5e1d948>
* merged_range_count: 0
* hbreaks: nil
* vbreaks: nil
* hbreaks_count: 0
* vbreaks_count: 0
* external_hyperlinks: #<FFI::Pointer address=0x00005582b318ea30>
* external_drawing_links: #<FFI::Pointer address=0x00005582b50e7300>
* drawing_links: #<FFI::Pointer address=0x00005582b22c3a00>
* panes: #<Libxlsxwriter::Panes:0x00005582b5e1cd68>
* protection: #<Libxlsxwriter::Protection:0x00005582b5e1c9d0>
* drawing: #<Libxlsxwriter::Drawing:0x00005582b5e1c6b0>
* list_pointers: #<Libxlsxwriter::WorksheetListPointers:0x00005582b5e1c200>
```



well, it is not really a big problem, as `pry-rails` is just for development

**Comment by fhsgoncalves** [comment]
I submit an attempt to fix it here: https://github.com/Paxa/fast_excel/pull/59

@Paxa, It worked well for me, could you check if the changes proposed are ok?

Thanks!
