### ISSUE TITLE
Not installed in Docker

### ISSUE THREAD

**Issue by rus-max** [Paxa/fast_excel#47]
```
current directory: /bundle/gems/fast_excel-0.2.6
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190910-1-97hcrj.rb extconf.rb

current directory: /bundle/gems/fast_excel-0.2.6
make "DESTDIR=" clean
make[1]: Entering directory '/bundle/gems/fast_excel-0.2.6/libxlsxwriter'
make[2]: Entering directory '/bundle/gems/fast_excel-0.2.6/libxlsxwriter/src'
make[2]: Leaving directory '/bundle/gems/fast_excel-0.2.6/libxlsxwriter/src'
make[2]: Entering directory '/bundle/gems/fast_excel-0.2.6/libxlsxwriter'
make[2]: *** test/unit: No such file or directory.  Stop.
make[2]: Leaving directory '/bundle/gems/fast_excel-0.2.6/libxlsxwriter'
make[1]: *** [Makefile:35: clean] Error 2
make[1]: Leaving directory '/bundle/gems/fast_excel-0.2.6/libxlsxwriter'
make: *** [Makefile:13: clean] Error 2

current directory: /bundle/gems/fast_excel-0.2.6
make "DESTDIR="
Compiling ext/text_width ...
rake compile
/bundle/gems/bundler-2.0.2/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'fast_excel' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
	from /bundle/gems/bundler-2.0.2/lib/bundler/resolver.rb:255:in `each'
	from /bundle/gems/bundler-2.0.2/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
	from /bundle/gems/bundler-2.0.2/lib/bundler/resolver.rb:49:in `start'
	from /bundle/gems/bundler-2.0.2/lib/bundler/resolver.rb:22:in `resolve'
	from /bundle/gems/bundler-2.0.2/lib/bundler/definition.rb:258:in `resolve'
	from /bundle/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
	from /bundle/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
	from /bundle/gems/bundler-2.0.2/lib/bundler/definition.rb:226:in `requested_specs'
	from /bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /bundle/gems/bundler-2.0.2/lib/bundler/runtime.rb:20:in `setup'
	from /bundle/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
	from /bundle/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /bundle/gems/spring-2.1.0/lib/spring/commands.rb:33:in `<module:Spring>'
	from /bundle/gems/spring-2.1.0/lib/spring/commands.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /bundle/gems/spring-2.1.0/lib/spring/server.rb:9:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /bundle/gems/spring-2.1.0/lib/spring/client/server.rb:9:in `call'
	from /bundle/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	from /bundle/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	from /bundle/gems/spring-2.1.0/bin/spring:49:in `<main>'
make: *** [Makefile:8: all] Error 1

make failed, exit code 2

```

**Comment by rus-max** [comment]
source 'https://rubygems.org'
gem 'rails', '5.2.3'
gem 'fast_excel'

RUBY_VERSION: '2.6.4'

**Comment by Paxa** [comment]
What image do you use? official ruby?

**Comment by Paxa** [comment]
Debian, slim, alpine?

**Comment by rus-max** [comment]
> Debian, slim, alpine?

Dockerfile:
FROM ruby:2.6.4

**Comment by srshkmr** [comment]
Same issue here. @rus-max Did you manage to resolve it?

I am using docker file ruby:2.4.2

**Comment by srshkmr** [comment]
Fixed the issue by upgrading to docker ruby:2.6.3

**Comment by full-of-foo** [comment]
I'm running:
> FROM ruby:2.4.5

Anyone have any other solutions that don't involve minor Ruby upgrades? ❤️

**Comment by full-of-foo** [comment]
Upgrading to `ruby:2.6.4` did not resolve the issue for me. My Dockerfile is as follows:

```
# Configure bundler and PATH
ENV GEM_HOME=/bundle
ENV BUNDLE_JOBS=4
ENV BUNDLE_RETRY=3
ENV BUNDLE_PATH=$GEM_HOME
ENV BUNDLE_APP_CONFIG=$BUNDLE_PATH
ENV BUNDLE_BIN=$BUNDLE_PATH/bin
ENV PATH /app/bin:$BUNDLE_BIN:$PATH

# Upgrade RubyGems and install required Bundler version
RUN gem update --system && \
    gem install bundler:2.0.2

WORKDIR /app

ENV RAILS_ENV=test
ENV NODE_ENV=test

# Install gems
ADD Gemfile* /app/
RUN bundle install \
 # Remove unneeded files (cached *.gem, *.o, *.c)
 && rm -rf /usr/local/bundle/cache/*.gem \
 && find /bundle/gems/ -name "*.c" -delete \
 && find /bundle/gems/ -name "*.o" -delete
```
```

**Comment by Paxa** [comment]
Released 0.3.0, sorry for delay
